Test(env): Test the chaosexperiment ENVs from secret and cm and fixes for node level chaos
litmuschaos/litmus-e2e pull request #247
Opened 2021-03-31 06:15 UTC by uditgaurav

Signed-off-by: udit <udit@chaosnative.com>

#### This PR includes:

- Addition of a new test: ENV test from secret and configMap which tests the litmus CRDs taking able to take the ENVs from secret and configMaps.
- Node level fixes according to the latest update in chaosengine CRs.
- There is a test in e2e which checks the node level chaos without appinfo, since now this mode is the default we will change without appinfo test to with appinfo test.

2021-04-06 09:04 UTC, Jonsy13 requested changes
@uditgaurav Looks good. Can we make the comment changes?

2021-04-10 07:21 UTC, ksatchit commented
We can do the with appinfo test for one of the node level exp: node-drain/taint/io-stress/restart

2021-05-13 09:36 UTC, oumkale approved these changes

2021-05-13 09:53 UTC, Jonsy13 approved these changes

2021-05-13 12:21 UTC, uditgaurav commented
The successful runs are:

- Component Tests:  https://github.com/litmuschaos/litmus-e2e/actions/runs/838786697
- Pod Level Tests:  https://github.com/litmuschaos/litmus-e2e/actions/runs/838787042

2021-05-13 12:45 UTC, merged