[Migrate]: Pod level pipeline from self hosted runner to shared runner
litmuschaos/litmus-e2e pull request #300
Opened 2021-08-20 10:02 UTC by uditgaurav

Signed-off-by: udit <udit@chaosnative.com>

## Details 

- Shift pod level pipeline clusters from kubeadm on ec2 to a transient kind/k3s cluster
- We can use a shared runner also in place of the self-hosted runner.
- The pipeline has a well-defined debug step to catch any test failure.

2021-08-21 16:25 UTC, oumkale approved these changes

2021-08-23 04:30 UTC, Jonsy13 requested changes

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      CHAOS_SERVICE_ACCOUNT: "${{ github.event.inputs.chaosServiceAccount }}"
This `chaosServiceAccount` input is not available in inputs array

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      OPERATOR_NAME: "${{ github.event.inputs.operatorName }}"
This `operatorName` input is not available in inputs array

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      APP_NS: "${{ github.event.inputs.chaosNamespace }}"
Same comments as above for inputs.

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
These both inputs `e2eTestRepo` & `e2eTestBranch` won't be available in scheduled pipelines

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/scheduled-pod-level-pipeline.yml
> +          repository: '${{ github.event.inputs.e2eTestRepo }}'
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      OPERATOR_NAME: "${{ github.event.inputs.operatorName }}"
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      OPERATOR_NAME: "${{ github.event.inputs.operatorName }}"
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      CHAOS_SERVICE_ACCOUNT: "${{ github.event.inputs.chaosServiceAccount }}"
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      CHAOS_SERVICE_ACCOUNT: "${{ github.event.inputs.chaosServiceAccount }}"
Same as above

2021-08-23 04:30 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      CHAOS_SERVICE_ACCOUNT: "${{ github.event.inputs.chaosServiceAccount }}"
Same as above

2021-09-06 08:39 UTC, Jonsy13 commented on .github/workflows/pod-level-pipeline.yml
> +      CHAOS_SERVICE_ACCOUNT: "${{ github.event.inputs.chaosServiceAccount }}"
PTAL `EXPERIMENT_IMAGE_PULL_POLICY: "${{ github.event.inputs.experimentImagePullPolicy }}"`, This is also not present in inputs array. Check in other places too.

2021-09-06 11:34 UTC, Jonsy13 approved these changes

2021-09-06 11:37 UTC, merged