add e2e dashboard folder
litmuschaos/litmus-e2e pull request #321
Opened 2021-10-12 14:54 UTC by Aman-Codes

# Description
Added the new e2e dashboard source code and build files which were earlier at [Aman-Codes/e2e-dashboard](https://github.com/Aman-Codes/e2e-dashboard).

# Screenshots
![image](https://user-images.githubusercontent.com/54680709/136979360-cd082e55-8c8a-484b-89c9-25b84efe56f6.png)
![image](https://user-images.githubusercontent.com/54680709/136979473-4cc026bb-202d-4809-8d5b-52b76b8c9049.png)
![image](https://user-images.githubusercontent.com/54680709/136979575-6f054630-403a-425c-a0f7-9a89e2cf40f5.png)

# Hosted URL
- https://aman-codes.github.io/litmus-e2e/dashboard/build/
- https://aman-codes.github.io/e2e-dashboard/

2021-10-13 03:05 UTC, Aman-Codes commented
> Thanks @Aman-Codes for the PR. Can you share the link of GitHub Pages hosted from your [forked e2e repository](https://github.com/Aman-Codes/litmus-e2e/tree/gh-pages)?

Hi @uditgaurav https://aman-codes.github.io/litmus-e2e contains the current dashboard and https://aman-codes.github.io/litmus-e2e/dashboard/build/ contains the new e2e dashboard

2021-10-13 04:58 UTC, uditgaurav commented
Can we update the pipeline description with right pipeline names like:
## For:

![image](https://user-images.githubusercontent.com/35391335/137069875-403e54f0-9c3a-4fd4-806e-16a9bfb638ef.png)
it can be "( GO BDDs) for the node-level pipelines"

2021-10-13 05:18 UTC, oumkale commented on dashboard/build/404.html
> +      var l = window.location;
You may use some relevant variables

2021-10-13 05:20 UTC, oumkale commented on dashboard/build/404.html
> +      var p = l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
Update relevant variable name for all

2021-10-13 05:23 UTC, oumkale commented on dashboard/build/index.css
> +/* Safari */
Will you remove unwated comments

2021-10-13 05:24 UTC, oumkale commented on dashboard/build/index.css
> +/* Safari */
Add relevant info about CSS styles Like where it is used

2021-10-13 05:25 UTC, Jonsy13 commented
Can we remove the build folder, we can use the github actions to build and push the same to gh-pages branch instead of pushing it manually, that way we will be able to test the build as well?

2021-10-13 05:28 UTC, oumkale commented on dashboard/build/service-worker.js
> +/**
Will you remove unwanted comments and add relevant comments

2021-10-13 05:28 UTC, Jonsy13 commented on dashboard/package.json
> +    "litmus-ui": "1.6.0",
You may also update the litmus-ui package, will enhance the performance.

2021-10-13 05:33 UTC, oumkale commented
@Aman-Codes There are a couple of files and CSS styling are reusable cc: @Jonsy13

2021-10-13 05:42 UTC, Jonsy13 requested changes

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/public/locales/en/translation.yaml
> +getStarted:
This file is not required, we are not using translation in dashboards, right? Also this file is for Portal not for dahsboard.

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/api/filterWorkflow.js
> +      if (element.name.match(/^Scheduled.*Pipeline$/) != null) {
It will be Nightly? @uditgaurav

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/api/sendRequest.js
> +  console.log("url inside sendRequest is", url);
Please remove all console logs

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/api/sendRequest.js
> +    console.log("response inside sendRequest is", response.data);
Here also

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/api/sendRequest.js
> +    console.log("Error inside sendRequest is", error);
Only display the error in this case... also console.error() should be used

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/CustomCard/index.jsx
> +  console.log("data inside CustomCard", data);
Same here

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/Header/ProfileDropDown.jsx
> +import React, { useState } from 'react';
These files are not required

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/Header/ProjectDropDown.jsx
> +import { IconButton, Popover, Typography } from '@material-ui/core';
Not required

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/Header/ProjectDropDownItems.jsx
> +import {
Not required

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/Header/index.jsx
> +                <LocalOfferIcon style={{paddingTop: 4}} /> 2.1.1 <StarBorder style={{paddingTop: 4}} /> 2.2k <AccountTree style={{paddingTop: 4}} /> 416
Version is not dynamic

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/Header/styles.js
> +  projectDropdown: {
Styles not required

2021-10-13 05:42 UTC, Jonsy13 commented on dashboard/src/components/Menu/index.jsx
> +import React, { useState } from 'react';
This is also not required.

2021-10-13 05:43 UTC, Jonsy13 commented
@Aman-Codes Please remove everything which is not related to dashboard

2021-10-13 05:50 UTC, Jonsy13 commented
![Screenshot from 2021-10-13 11-18-56](https://user-images.githubusercontent.com/40681425/137074572-991e744f-4e37-4615-9e3c-8f183a34a88a.png)

For Portal pipeline, the commit ids should be taken from litmuschaos/litmus Repo

2021-10-13 05:54 UTC, oumkale commented on dashboard/src/components/Header/ProjectDropDownItems.jsx
> +    // eslint-disable-next-line no-alert
Same

2021-10-13 05:56 UTC, oumkale commented on dashboard/src/components/Header/index.jsx
> +// import ProjectDropdown from './ProjectDropDown';
Same

2021-10-13 05:56 UTC, oumkale commented on dashboard/src/components/Header/index.jsx
> +            <ProfileDropdown />
Remove this if it is not required

2021-10-13 05:57 UTC, oumkale commented on dashboard/src/components/SideBar/index.jsx
> +  // const handleManual = () => {
Same

2021-10-13 05:58 UTC, oumkale commented on dashboard/src/components/SideBar/index.jsx
> +          key="litmusAPIDocs"
Remove all if it is not required

2021-10-13 05:59 UTC, oumkale commented on dashboard/src/components/Table/TimelineComponent.jsx
> +    in_progress
Remove all if it is not required

2021-10-13 06:00 UTC, oumkale commented on dashboard/src/components/Table/helper.js
> +  neutral
Same

2021-10-13 06:01 UTC, oumkale commented on dashboard/src/containers/app/Routes.jsx
> +          {/* <Route exact path="/scheduled-runs/:pipelineName" render={(props) => <ScheduledRuns {...props} />} /> */}
Remove unwanted routes

2021-10-13 06:01 UTC, oumkale commented on dashboard/src/containers/layouts/Scaffold/index.jsx
> +        <SideBar scheduledData={scheduledData} manualData={manualData}/>
Remove this if not require

2021-10-13 06:08 UTC, oumkale commented
Hi @Aman-Codes,

 - Add function details for every function used
 - Remove all unwanted comments and unused code
 - Follow proper lint format, Many places spaces, newline and all not formatted
 - Use all heading and info from the manifest. Take ref from litmus-portal
 - Make command functions reusable, same for CSS. cc: @Jonsy13

2021-10-13 12:50 UTC, Aman-Codes commented on dashboard/src/components/CustomCard/index.jsx
> +          <Button size="small">Pipeline Details</Button>
Did you meant to put all the text visible on user screen under a single file like https://github.com/litmuschaos/litmus/blob/master/litmus-portal/frontend/public/locales/en/translation.yaml ?

2021-10-13 13:00 UTC, Jonsy13 requested changes

2021-10-13 16:37 UTC, Aman-Codes commented on dashboard/public/404.html
> +      var updatedLocation = l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
Updated It

2021-10-14 06:22 UTC, Jonsy13 approved these changes
Please check the build process. @uditgaurav @Aman-Codes 
Pushing the build folder is not a good practice. We cannot review the autogenerated build files.

2021-10-14 15:01 UTC, merged