Draft PR for chaoscenter e2e testing
litmuschaos/litmus-e2e pull request #405
Opened 2024-03-30 06:30 UTC by Dhanush0369

## Proposed changes

Summarize your changes here to communicate with the reviewers and make sure to put the link of the related issue

## How has this been tested:
- [ ] Test environment
    * [ ] GKE
    * [ ] AWS
    * [ ] OpenShift
    * [ ] KinD/k3s/k3d cluster
    * [ ] Others
 - [ ] Tested with production environment ( For ChaosCenter Tests )
 - [ ] Have not tested

## Types of changes

What types of changes does your code introduce to Litmus? Put an `x` in the boxes that apply
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices applies)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.
- [ ] I have read the [CONTRIBUTING](https://github.com/litmuschaos/litmus-e2e/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the commit for DCO to be passed.
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added Screenshots or Terminal snippets in the PR comment to validate the successful execution of changes

**Documentation**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] data-cy=* parameters have been added in codebase ( ChaosCenter Tests )
- [ ] data-cy=* parameters need to be added in codebase ( ChaosCenter Tests )
- [ ] No updates required.

**Code Review**
- [ ] Does the test handle fatal exceptions, ie. uncaught exceptions from 3rd party library (if any)

**Issue**
- [ ] Tasks in issue are checked off

## Dependency
- Please add the links to the dependent PR need to be merged before this (if any).

## Special notes for your reviewer:

2024-03-31 16:45 UTC, namkyu1999 requested changes
Hi @Dhanush0369, Can you move all of the changes to the `Cypress` dir?

guide: https://github.com/litmuschaos/litmus-e2e/blob/master/Cypress/Readme.md

2024-04-19 11:38 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/UserManagment.cy.js
> +describe('testing UserManagement', () => {
```suggestion
describe('Test Cases for User-Management', () => {
```

2024-04-19 11:41 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/UserManagment.cy.js
> +          };
We can shift this to fixtures & use from there.

Example - https://github.com/litmuschaos/litmus-e2e/blob/master/Cypress/cypress/fixtures/Users.json
Usage - https://github.com/litmuschaos/litmus-e2e/blob/d8cbeaf8661de20da49b6fa62146eafa5202f489/Cypress/cypress/integration/Basic_Setup/1.%20Login/login.spec.js#L18

2024-04-19 11:44 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/UserManagment.cy.js
> +        //edit password
@Dhanush0369 Can we shift this into it's own it() block.

Structure we can follow could be either - 

```
describe("API Tests"){
  it(create)
  it(edit)
  it(delete)
}

describe("UI Tests"){
  it(create)
  it(edit)
  it(delete)
}
```

OR

Have UI tests in one file & API tests in other.

2024-04-19 11:47 UTC, Jonsy13 commented on chaoscenter/cypress/support/commands.js
> +    cy.get('.bp3-button').click({ });
Can we check if there is some other selector we can use?
e.g. like `cy.get('button[label=""]')` or `cy.contains('button',"some text on button")`

2024-04-19 11:49 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/negative_tests.cy.js
> +import { add_hub } from "../fixtures/chaoshub";
It would be better to have negative tests in same file where we have positive tests.
One file per feature would be better.

2024-04-19 11:49 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/login.cy.js
> +  it('testing login thorugh REST API', () => {
```suggestion
  it('testing login via REST API', () => {
```

2024-04-19 11:50 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/login.cy.js
> +  it('testing login with valid data', () => {
```suggestion
  it('testing login via UI', () => {
```

2024-04-19 11:51 UTC, Jonsy13 commented on chaoscenter/cypress/e2e/UserManagment.cy.js
> +        cy.get('input[name="reEnterPassword"]').type('User22222');
we can shift this data as well to fixture

2024-04-27 04:07 UTC, namkyu1999 commented
Hi @Dhanush0369 , Can you also REAMDE.md(installation & setup guide) in `/chaoscenter` dir?

2024-04-27 12:30 UTC, namkyu1999 requested changes
I got some errors when testing...
1. `UserManagement`
![Screenshot 2024-04-27 at 9 22 02 PM](https://github.com/litmuschaos/litmus-e2e/assets/53862866/1e1ac9d1-7134-4e48-8b6a-642fff06b105)
2. `ChaosProbes`
![Screenshot 2024-04-27 at 9 23 53 PM](https://github.com/litmuschaos/litmus-e2e/assets/53862866/064246f6-383c-4672-9f38-184f3177619d)
3. `chaoshub`
![Screenshot 2024-04-27 at 9 25 35 PM](https://github.com/litmuschaos/litmus-e2e/assets/53862866/084d5d08-e95b-471b-824e-c0a2a10c98d4)
4. `chaosinfra`
![Screenshot 2024-04-27 at 9 27 42 PM](https://github.com/litmuschaos/litmus-e2e/assets/53862866/24f7f7f5-cb9e-4433-8397-bdceb8a07a7f)
5. `negative_tests`
![Screenshot 2024-04-27 at 9 28 51 PM](https://github.com/litmuschaos/litmus-e2e/assets/53862866/8c04b233-2f2c-46b4-b134-0fcb9885b04c)


can you check them?

2024-05-09 11:17 UTC, namkyu1999 approved these changes

2024-05-14 10:04 UTC, Jonsy13 approved these changes

2024-05-15 11:58 UTC, imrajdas approved these changes

2024-05-15 11:58 UTC, merged